name: Deploy Development

on:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-initial-infra:
    uses: ./.github/workflows/deploy-initial-infra.yml
    with:
      terraform_workspace: node-app
    secrets: inherit

  build-app-image:
    needs: ["deploy-initial-infra"]
    uses: ./.github/workflows/build-app.yml
    with:
      ecr_repo: prod-node-app
      region: eu-west-1
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-infra:
    needs: ["build-app-image"]
    uses: ./.github/workflows/deploy-infra.yml
    with:
      terraform_workspace: node-app
    secrets: inherit
